


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nurlaila Ramadhani
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }
    
    private void new1actionPerformed(java.awt.event.ActionEvent evt){
        MenuUtama menubaru = new MenuUtama();
        menubaru.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        MenuJenisBarang = new javax.swing.JMenuItem();
        MenuDataBarang = new javax.swing.JMenuItem();
        MenuDataDistributor = new javax.swing.JMenuItem();
        MenuDataPetugas = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuBarangMasukT = new javax.swing.JMenuItem();
        MenuPenjualanBarangT = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(212, 234, 247));

        Menu1.setBackground(new java.awt.Color(212, 234, 247));
        Menu1.setText("File");
        Menu1.setPreferredSize(new java.awt.Dimension(64, 22));

        MenuJenisBarang.setText("Data Jenis Barang");
        MenuJenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuJenisBarangActionPerformed(evt);
            }
        });
        Menu1.add(MenuJenisBarang);

        MenuDataBarang.setText("Data Barang");
        MenuDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataBarangActionPerformed(evt);
            }
        });
        Menu1.add(MenuDataBarang);

        MenuDataDistributor.setText("Data Distributor");
        MenuDataDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataDistributorActionPerformed(evt);
            }
        });
        Menu1.add(MenuDataDistributor);

        MenuDataPetugas.setText("Data Petugas");
        MenuDataPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataPetugasActionPerformed(evt);
            }
        });
        Menu1.add(MenuDataPetugas);

        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        Menu1.add(MenuExit);

        jMenuBar1.add(Menu1);
        Menu1.getAccessibleContext().setAccessibleDescription("");

        jMenu2.setBackground(new java.awt.Color(212, 234, 247));
        jMenu2.setText("Transaksi");

        MenuBarangMasukT.setText("Data Barang Masuk");
        MenuBarangMasukT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangMasukTActionPerformed(evt);
            }
        });
        jMenu2.add(MenuBarangMasukT);

        MenuPenjualanBarangT.setText("Data Penjualan Barang");
        MenuPenjualanBarangT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPenjualanBarangTActionPerformed(evt);
            }
        });
        jMenu2.add(MenuPenjualanBarangT);

        jMenuBar1.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(212, 234, 247));
        jMenu1.setText("Report");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuJenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuJenisBarangActionPerformed
        // TODO add your handling code here:
        new formjenis().setVisible(true);
    }//GEN-LAST:event_MenuJenisBarangActionPerformed

    private void MenuDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataBarangActionPerformed
        // TODO add your handling code here:
        new formbarang().setVisible(true);
    }//GEN-LAST:event_MenuDataBarangActionPerformed

    private void MenuDataDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataDistributorActionPerformed
        // TODO add your handling code here:
        new FormDistributor().setVisible(true);
    }//GEN-LAST:event_MenuDataDistributorActionPerformed

    private void MenuDataPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataPetugasActionPerformed
        // TODO add your handling code here:
        new FormPetugas().setVisible(true);
    }//GEN-LAST:event_MenuDataPetugasActionPerformed

    private void MenuBarangMasukTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangMasukTActionPerformed
        // TODO add your handling code here:
        new barangmasuk().setVisible(true);
    }//GEN-LAST:event_MenuBarangMasukTActionPerformed

    private void MenuPenjualanBarangTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPenjualanBarangTActionPerformed
        // TODO add your handling code here:
        new penjualan().setVisible(true);
    }//GEN-LAST:event_MenuPenjualanBarangTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenuItem MenuBarangMasukT;
    private javax.swing.JMenuItem MenuDataBarang;
    private javax.swing.JMenuItem MenuDataDistributor;
    private javax.swing.JMenuItem MenuDataPetugas;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuJenisBarang;
    private javax.swing.JMenuItem MenuPenjualanBarangT;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
